import { useEffect, useState } from "react";
import api from "../services/api";
import {RiSparkling2Line } from "react-icons/ri"
import toast from "react-hot-toast";

const SummaryModal = ({ note, isOpen, onClose }) => {
const [summary, setSummary] = useState("");
const [loading, setLoading] = useState(false);
const [visibleSummary, setVisibleSummary] = useState("");

useEffect(() => {
if (!isOpen || !note) return;


const fetchSummary = async () => {
  try {

    const aiSummary = note.summary
      ? note.summary
      : (await api.post(`/notes/${note._id}/summarize`)).data.summary;
    setLoading(true);
    await new Promise(resolve => setTimeout(resolve, 2000));
    setLoading(false);
    setSummary(aiSummary);
    setVisibleSummary("");
    let current = "";
    for (const char of aiSummary) {
      current += char;
      setVisibleSummary(current);
      await new Promise(resolve =>
        setTimeout(resolve, 15)
      );
    }
  } catch (error) {
    setLoading(false);
    toast.error("Failed to generate AI summary. Please try again.");
    console.error(error);
  }
};

fetchSummary();


}, [isOpen, note]);

if (!isOpen || !note) return null;

return ( <div
   className="
     fixed inset-0
     z-50
     flex items-center justify-center
     bg-black/70
     backdrop-blur-md
     p-4
   "
 > <div
     className="
       relative
    w-full
    max-w-3xl
    max-h-[85vh]
    rounded-3xl
    border border-white/10
    bg-zinc-950/95
    backdrop-blur-xl
    shadow-[0_0_80px_rgba(139,92,246,0.08)]
    overflow-hidden
    flex
    flex-col
     "
   >
 <div
       className="
         absolute
         top-0
         left-0
         right-0
         h-px
         bg-linear-to-r
         from-transparent
         via-violet-500
         to-transparent
       "
     />


<div className="p-8 flex flex-col flex-1 overflow-hidden">

      <div className="flex items-center justify-between mb-8">

        <div className="flex items-center gap-2">
          <div className="h-3 w-3 rounded-full bg-red-500" />
          <div className="h-3 w-3 rounded-full bg-yellow-500" />
          <div className="h-3 w-3 rounded-full bg-green-500" />
        </div>

        <button
          onClick={onClose}
          className="
            h-10
            w-10
            rounded-xl
            border border-white/10
            bg-white/5
            text-zinc-400
            transition-all
            duration-300
            hover:bg-white/10
            hover:text-white
          "
        >
          ✕
        </button>

      </div>

      <div className="mb-8">

        <div
          className="
            inline-flex
            items-center
            gap-2
            px-4
            py-2
            rounded-full
            border border-violet-500/20
            bg-violet-500/5
            text-violet-300
            text-sm
            mb-4
          "
        >
           <RiSparkling2Line className="h-4 w-4" />
          AI Generated Summary
        </div>

        <h2 className="text-3xl font-bold tracking-tight text-white">
          {note.title}
        </h2>

        <p className="text-zinc-500 mt-2">
          Smart insights generated by Synapse AI
        </p>

      </div>

     <div className="flex-1 overflow-y-auto pr-2">

        {loading ? (

          <div
            className="
              flex
              flex-col
              items-center
              justify-center
              py-20
            "
          >
            <div
              className="
                h-12
                w-12
                rounded-full
                border-2
                border-violet-500/20
                border-t-violet-500
                animate-spin
              "
            />

            <p className="mt-5 text-zinc-400">
              Generating AI Summary...
            </p>

          </div>

        ) : (

          <div
            className="
              rounded-2xl
              border border-violet-500/15
              bg-violet-500/[0.04]
              p-6
            "
          >
            <p
              className="
                whitespace-pre-wrap
                wrap-break-words
                text-zinc-300
                leading-8
                text-[16px]
              "
            >
              {visibleSummary}
            </p>
          </div>

        )}

      </div>

    </div>
  </div>
</div>


);
};

export default SummaryModal;
